### ISSUE TITLE
Template for files

### ISSUE THREAD

**Issue by micahmicah** [risd/wh-info#18]
Not sure how to really describe this.

Searched for "Installation site Permit" and the first result took me here:

http://info.risd.edu/filesforlinks/installation-site-permit/

Which looks like a url specifically for files. Not a bad idea at all! but it seems like we should have some sort of template or structure for when someone lands here.

**Comment by mmarol** [comment]
huh

**Comment by mmarol** [comment]
also, you can just reply via email. cool.

**Comment by cmiller02** [comment]
Hey Guys,

You may have already dealt with this, but it looks like it's displaying the
"links for files" content type that Jay created for the first two search
results.  The next four links that it gives are what I would expect to see:

- Environmental Health and Safety
- Facilities Operations
- Public Safety
- Risk Management

All four of these pages contain a link to the installation site permit.

-Carrie

Carrie J. Miller
Marketing Coordinator
RISD MEDIA GROUP
Rhode Island School of Design
cmiller02@risd.edu (401) 454-6346
