### ISSUE TITLE
Quicklinks not coming up in info's search

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#21]
Hi Jay,

You and I both realized that the quicklinks don't seem to come up as results when doing a search of info on info.

Thanks,
Carrie

**Comment by mmarol** [comment]
Really not sure how to get this working.

**Comment by cmiller02** [comment]
I did a couple of Useful Links item searches on info.risd.edu and it seems like they're being picked-up now!

<img width="1190" alt="screen shot 2018-01-08 at 3 17 07 pm" src="https://user-images.githubusercontent.com/14020234/34690497-6d4ebb46-f487-11e7-9145-38cdd6af1fd3.png">
<img width="1188" alt="screen shot 2018-01-08 at 3 19 30 pm" src="https://user-images.githubusercontent.com/14020234/34690499-6d57a224-f487-11e7-8d0b-f299d44c551e.png">
<img width="1168" alt="screen shot 2018-01-08 at 3 21 37 pm" src="https://user-images.githubusercontent.com/14020234/34690571-b34cf5d6-f487-11e7-813c-5c7b20f5709e.png">

Do you think we can close out this issue Ruben?

**Comment by cmiller02** [comment]
Made these results even better with swiftype. Now the "RISD Info - Useful Links" come up first and I eliminated the less good/redundant ones like in the screenshot above that only have "RISD Info" as the page title:

![screen shot 2018-02-15 at 3 24 14 pm](https://user-images.githubusercontent.com/14020234/36279255-778a322a-1264-11e8-8fde-9053cfa3f1ab.png)
![screen shot 2018-02-15 at 3 24 36 pm](https://user-images.githubusercontent.com/14020234/36279265-7d2218f6-1264-11e8-99e2-85b6da1c1b9a.png)
![screen shot 2018-02-15 at 3 24 56 pm](https://user-images.githubusercontent.com/14020234/36279270-821bb0ce-1264-11e8-9638-b618b7f1ff63.png)


 Going to close out this issue now.
