### ISSUE TITLE
Brian noticed two risd campus maps in google

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#22]
Hey Jay,

When Brian googled risd campus map PDF he found two links stemming from info:

http://info.risd.edu/webhook-uploads/1441734335142/RISD%20Campus%20Basemap%20(3)-1.pdf

and this older one that stars 123 Dyer Street: http://info.risd.edu/webhook-uploads/1434558370594/RISD%20Campus%20Basemap%20with%20123%20Dyer%20star%20(1).pdf

Would you be able to find/eliminate the second one?

Thanks,
Carrie

**Comment by mmarol** [comment]
The extra map is in the Facilities Management page right at the bottom. I will leave the decision of whether or not to delete it to you. I will also add the document link option as per issue #20 so that you can include the same document in multiple places without reuploading.

**Comment by cmiller02** [comment]
This issue is no longer relevant, as the search results are now different. Running this search again did give me another thing to take care of, but that is outside the scope of this request. So, I'm going to close this issue.
