### ISSUE TITLE
Getting Rid of Old Files

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#24]
Hey Jay,

A few weeks back, on the Accounts Payable page, I swapped-out the "Honorarium Request - Domestic" file in the Documents/Downloads/Forms area.  I forgot to also do this for the "Honorarium Payment Form" link in the Honoraria Payment Process area.  This has been remedied now, but Brian pointed out that we need a way to go in and delete old files, like in this case when a form gets redone and I have to swap out the file.  I know that I could do this in the Files for Links area, but what about files that I just upload on office pages in html areas or in the Documents/Downloads/Forms area?

Thanks,
Carrie

**Comment by mmarol** [comment]
I think if you replace/delete a file in the Documents/Downloads/Forms it should get rid of the previous file. Webhook keeps a backup of the data automatically for a week I think, so maybe the files stays on the server for a week after it's deleted. Not 100% sure, so I will check with webhook

**Comment by cmiller02** [comment]
Now that info is on google cloud platform we can close out this issue, right? (I've been deleting old versions of files using GCP since Ruben moved info onto it.)

**Comment by rubillionaire** [comment]
@cmiller02 yup, that sounds right to me. We now have the ability to delete files in GCP.
