### ISSUE TITLE
Creating an optional fax# field

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#29]
Hey Jay,

When you can, can you please create a field for a fax number on info pages that would be situated in the right-hand office information column, maybe below the phone number field.  If you could make it so it will only appear when filled-in that would be great, as not many offices need this.

Thanks!
-Carrie

**Comment by rubillionaire** [comment]
This field is now in, and live on http://info.risd.systems. If it looks good, we can get it ready for info.risd.edu.

**Comment by cmiller02** [comment]
Thanks Ruben! This looks great and is now live on both info.risd.systems and info.risd.edu. As a test I put Media Group's fax number in and here is how it displays:

<img width="243" alt="screen shot 2018-01-08 at 10 20 50 am" src="https://user-images.githubusercontent.com/14020234/34677318-c05dd1a2-f45d-11e7-8189-bc2fd947aa35.png">

**Comment by cmiller02** [comment]
@rubillionaire - since this isn't live on info.risd.edu now, after your rollback, I think this is another one that is ready to go live! Thanks!

**Comment by rubillionaire** [comment]
I am going to close this now that it is live on info.risd.edu.
