### ISSUE TITLE
Way to easily skip down the page alphabetically

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#33]
Hey Jay,

Would it be possible to do an A-Z index to allow people to skip down the homepage of info more quickly?  Here's what I found as an example after one quick search, but you probably know of other methods: http://www.utah.edu/a-z/

Just thought this might improve user experience.

Thanks,
Carrie

**Comment by rubillionaire** [comment]
A version of this is now live on http://info.risd.systems/

Let me know how it looks!

**Comment by cmiller02** [comment]
Hi Ruben.  This looks great! And it looks like it's already live on info.risd.edu too - which is totally fine! Thank you!

**Comment by rubillionaire** [comment]
Funny you should say that, Carrie. I started with the list left aligned, and it was bugging me that the items didn't really end up in a grid as you'd hope. It gets more skewed the further to the right you go. So I thought that removing the notion of the grid and center aligning would be best.

left aligned:

<img width="1342" alt="screen shot 2018-01-17 at 4 01 34 pm" src="https://user-images.githubusercontent.com/434737/35066799-e0fb1142-fb9f-11e7-81e6-636b7527d344.png">

centered:

<img width="1342" alt="screen shot 2018-01-17 at 4 04 12 pm" src="https://user-images.githubusercontent.com/434737/35066881-1d674c36-fba0-11e7-841f-4a77004e89cf.png">


Let me know what you think, I'm down to go either way on this.

& sorry about the early release to info.risd.edu. I pulled back on that error so we have our proper staging environment here on info.risd.systems to verify.

**Comment by cmiller02** [comment]
@rubillionaire - thanks so much for the experimentation on this. I actually like the left-aligned, first option, if that's ok. Do you mind moving ahead with that? Thanks!

**Comment by cmiller02** [comment]
looks perfect, @rubillionaire ! Thanks so much. I think we're good to go live with this. YAY!

**Comment by rubillionaire** [comment]
I am going to close this now that it is live on info.risd.edu.
