### ISSUE TITLE
Color-Blind Issue

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#34]
Hey Jay,

You might remember that the issue of people who are color blind not easily seeing the search bar came up a bit ago.  Would it maybe be good to make the word "Search" the beige background color used on info?  Whatever you think would work, though - I guess the word "Search" maybe just doesn't have enough contrast given the color of the orange strip at the top that it's on.

Thanks,
Carrie

**Comment by rubillionaire** [comment]
This is now live on http://info.risd.systems. Let me know how it looks to you. If its all good, we can merge it into info.risd.edu the next time around.

**Comment by cmiller02** [comment]
Hi Ruben. This looks great, and I actually think it's already live on info.risd.edu.

Thanks!

**Comment by rubillionaire** [comment]
I pulled back on the deploy, but I will go ahead and close this issue in anticipation of merging info.risd.systems into info.risd.edu tomorrow.

**Comment by cmiller02** [comment]
Thanks @rubillionaire !
