### ISSUE TITLE
End of line words getting split with hyphens, rather than completely going to next line

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#41]
I know that this was happening in Safari a while ago, but now it seems to be happening in Chrome too.  I just checked - this is currently happening in Chrome and Safari, but is fine in Firefox.  Here is a screenshot from Chrome:

![screen shot 2017-04-12 at 1 29 40 pm](https://cloud.githubusercontent.com/assets/14020234/24971038/7dc299b2-1f84-11e7-8a47-11233eb48cab.png)

**Comment by rubillionaire** [comment]
This is now in, and live on http://info.risd.systems. If it looks good, we can get it ready for info.risd.edu.

**Comment by cmiller02** [comment]
Hey Ruben,

I thought we were good to go, but then I noticed that we're still getting some breaking in bullet points in Safari and Chrome:
![screen shot 2018-01-08 at 8 56 45 am](https://user-images.githubusercontent.com/14020234/34673947-031e5126-f452-11e7-9cd9-d01e6a21f40c.png)

I think we're doing well within <p> tags, though!

Thanks,
Carrie

**Comment by rubillionaire** [comment]
Ahh I'm not as familiar with these style sheets, but I am getting a better understanding. Thanks for showing me another context where hyphens were a problem.

I've gone ahead and added the hyphen removal to any context that has a body of text. Hopefully I got them all, but let me know if there are still hyphens showing up somewhere.

**Comment by cmiller02** [comment]
I see this happening in bullets on the Counseling page in Chrome:
![screen shot 2018-01-18 at 10 04 19 am](https://user-images.githubusercontent.com/14020234/35104525-0fdf35a0-fc37-11e7-999b-75fb3ae79187.png)

Do you see how on the third bullet, when at this size, the first line ends with "con-"
and the fourth bullet, the first line, ends with "im-"

And here is a non bullet instance on the Accounts Payable page:
![screen shot 2018-01-18 at 10 08 40 am](https://user-images.githubusercontent.com/14020234/35104753-c4ba2b92-fc37-11e7-9a1c-66cfcd03db65.png)

"(reimberse-", "de-" and "ad-" in the second and third paragraphs

Is it possible that you're only affecting the office description/opening paragraph? I don't see breaking in that area, but in the subpages/sub sections I do.

**Comment by cmiller02** [comment]
Things look perfect, @rubillionaire - thank you! I checked on Chrome, Safari, and Firefox and all look good. I think that this is ready to go live.

**Comment by rubillionaire** [comment]
I am going to close this now that it is live on info.risd.edu.
