### ISSUE TITLE
Files in "Files For Links" area don't open in a new tab

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#42]
Example:

I added, in Files for Links today, the Science for Art and Design Education Courses, 17-18 PDF.  I then put that, in the Documents/Downloads/Forms area, on these 2 pages:

[http://info.risd.edu/history-philosophy-and-the-social-sciences/#related-content](url) and
[http://info.risd.edu/natureculturesustainability-studies-ncss/#related-content](url)

I would like the links to this PDF to open in new tabs, as the other (non Files for Links) Docs/Dwnlds/Forms do. Can you make a rule that all Files for Links will open in a new tab?

Thanks!
-Carrie

**Comment by rubillionaire** [comment]
Hey, Carrie. This issue looks like its complete to me. The links you referenced have the markup for them to open in a new tab.

I am going to close this for now, but feel free to reopen with some other examples if there are others to address.
