### ISSUE TITLE
Having Side Nav Items Display on Desktop, versus using Hamburger Menu

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#43]
Hey Jay,

Would it be possible, in desktop view, for side nav items to display on an office's page, rather than be in the form of the hamburger menu.  From feedback I've gotten it seems that people, on a desktop, think that clicking the hamburger is weird and they just want to see the nav.  I think for tablet and phone we're fine with the hamburger, but if we could eliminate it for the desktop and just have the links show that would be preferable to people, I think.

Thanks,
Carrie

**Comment by rubillionaire** [comment]
@cmiller02 I have updated info.risd.systems to include this change. The page I kept referring to while developing this was the [Accounts Payable page](http://info.risd.systems/accounts-payable/), since it has so many sub pages.

Let me know how this looks to you! If everything is good to go, I'll merge it into the templates for info.risd.edu.

**Comment by cmiller02** [comment]
Hey @rubillionaire - would you mind just making one small tweak. Could you double the space between the line that is under "20 Washington Place" and the word "Payment Request" so that there's a little separation between the contact info stuff and the start of the nav?:
![screen shot 2018-01-24 at 9 13 22 am](https://user-images.githubusercontent.com/14020234/35336738-5bc58c62-00e7-11e8-81d9-5943b8f8bfb6.png)

Thank you!

**Comment by rubillionaire** [comment]
No problem, @cmiller02. I bumped up the space between the basic info and the links. Let me know how that looks. I'd be happy to make it smaller or bigger.

**Comment by cmiller02** [comment]
Looking good, @rubillionaire! I asked Jay M for a little design advice on this, as I felt we weren't quite there yet and he thinks that it might be good to remove all of the grey lines EXCEPT for the one below "20 Washington Place" - that way we get the idea I was going for of the contact info in a cluster at top and the links in a cluster below. After removing the lines could you try giving half the space between the contact items - so half the space between "8:30 am - 4:30 pm" and the word "Phone," as an example. Thanks so much!

**Comment by rubillionaire** [comment]
@cmiller02 I pushed another update that removes the lines between the basic info and side bar nav items, and places a line between the two sections. Check it out and let me know what you think of it! http://info.risd.systems/accounts-payable/

**Comment by cmiller02** [comment]
This is looking great, @rubillionaire! Thank you!  My only question is about the width of the area where the links are on the right. I see that, on a large screen like the one I'm on at my desk here, that if I enlarge the width of the window the links go from looking like this (this is a window size about half the width of my screen):
![screen shot 2018-01-31 at 12 22 59 pm](https://user-images.githubusercontent.com/14020234/35637208-8ca5e864-0681-11e8-98b2-711c1152d3a2.png)

to this (this is a window size the entire width of my screen):
![screen shot 2018-01-31 at 12 21 47 pm](https://user-images.githubusercontent.com/14020234/35637216-9835e71a-0681-11e8-8542-e45282dd0b00.png)

Would it be possible to have the minimum width of that link area be bigger by default at desktop view, so that even if I'm not dragging my window to be really wide that we get more of this kind of feel:
![screen shot 2018-01-31 at 12 21 47 pm](https://user-images.githubusercontent.com/14020234/35637320-da8ed126-0681-11e8-8c4a-0445b74a2150.png)

(basically I think it might be good if the menu was always the above with on a desktop view, since we definitely seem to have the beige space to spare to the right of it.) I just like it better when individual link names don't have to go onto two lines as much.

**Comment by rubillionaire** [comment]
Definitely, @cmiller02 . The whitespace on the right of the desktop sidebar is pretty generous. I went ahead and added another column's worth of space to the sidebar, taking away from the width of the white space. Let me know what you think!

http://info.risd.systems/accounts-payable/

**Comment by cmiller02** [comment]
I love it, @rubillionaire - perfect! I think we're good to push this to the live site - yay!

**Comment by rubillionaire** [comment]
Awesome! Its just been pushed out into the wider world of info.risd.edu. I'll go ahead and close this issue, and all of the others that got included as part of this latest push.

Thanks, @cmiller02!
