### ISSUE TITLE
Fix broken asset links

### ISSUE THREAD

**Issue by rubillionaire** [risd/wh-info#44]
Carrie got an email from Accounts Payable reporting some broken links on their page. After digging into it, I found a few more. I figured I would make an issue to discuss around if further work should need to occur around the topic.

There is a full list of the previously broken links below, and their new locations, which have been updated in the CMS. These three links were not able to be recovered, since they were still pointing at the old risd.edu file structure.

- http://www.risd.edu/uploadedFiles/RISD_edu/Students/Public_Safety/ncpc.pdf
- http://www.risd.edu/uploadedFiles/RISD_edu/Students/Policies/Conduct/EthicsPoint-FAQ-020912.pdf
- http://www.risd.edu/uploadedFiles/RISD_edu/Students/Policies/Conduct/RISD_Whistleblower_Process.pdf

### Successful links created.

previously broken link: http://info.webhook.org/webhook-uploads/1462891464401/sade_course_catalog_list_2016_2017.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508550116240_sade_course_catalog_list_2016_2017.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1458305290813/risd_final_2016ss.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434822660_risd_final_2016ss.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1485444299690/risd_rides_route_1.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434830189_risd_rides_route_1.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1485444355871/risd_rides_route_2.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434831123_risd_rides_route_2.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1484933200810/wyndham.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434829410_wyndham.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1485986924715/partner_hotel_quick_reference_sheet_for_distribution_with_travel_portal_instrs_2017.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434831918_risd_partner_hotels_quick_reference_sheet_9_13_17.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1473438354305/uhcg_scholastic_insurance_id_card_risd.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434828454_uhcg_scholastic_insurance_id_card_risd.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1467815626104/how_to_proactively_safeguard_your_apple_mac_computer.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434824890_how_to_proactively_safeguard_your_apple_mac_computer.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1467815737347/how_to_proactively_safeguard_your_windows_computer.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434825778_how_to_proactively_safeguard_your_windows_computer.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1442598540096/Pantry2U.xlsx
new active link: https://cdn.risd.systems/webhook-uploads/1508435077374_Pantry2U.xlsx

previously broken link: http://info.webhook.org/webhook-uploads/1462204605508/honorarium_request_domestic_112315-2.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508550568949_honorarium_request_domestic_112315-2.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1441987278311/RISD%20Independent%20Contractor%20Checklist%20FINAL.doc
new active link: https://cdn.risd.systems/webhook-uploads/1508434806520_RISD%2520Independent%2520Contractor%2520Checklist%2520FINAL.doc

previously broken link: http://info.webhook.org/webhook-uploads/1453475237701/14-15_facultystaffguide_rev.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434814891_14-15_facultystaffguide_rev.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1453478508298/newaaweb_brochure.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434815919_newaaweb_brochure.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1453993915863/accommodation_request_timeline.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434816784_accommodation_request_timeline.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1453994332693/application_for_services.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434817652_application_for_services.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1453994624450/support_animals.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434819349_support_animals.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1486571055384/parking_appeals.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434837667_parking_appeals.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1486571366849/parking_spaces_map.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508435033790_parking_spaces_map.pdf

previously broken link: http://info.webhook.org/webhook-uploads/1486572492211/risd_parking_permit_rates.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434838573_risd_parking_permit_rates.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1443018344010/BEB%20MODEL%20SHOP%20AND%20LASER%20CUTTER%20SCHEDULE%20%202015.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434873238_BEB%2520MODEL%2520SHOP%2520AND%2520LASER%2520CUTTER%2520SCHEDULE%2520%25202015.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1504709642491/travel_and_expense_form_9_6_17.xlsx
new active link: https://cdn.risd.systems/webhook-uploads/1508434841256_travel_and_expense_form_9_6_17.xlsx

previously broken link: http://info.risd.edu/webhook-uploads/1441734335142/RISD%20Campus%20Basemap%20(3)-1.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508550768435_RISD%2520Campus%2520Basemap%2520(3)-1.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1492001315671/sade_course_list_2017_2018.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434823819_sade_course_list_2017_2018.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1442600108281/Pizza%20Delivery%20Menu.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508435013401_Pizza%2520Delivery%2520Menu.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1472734272010/alcohol_use_and_regulations_form.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434827432_alcohol_use_and_regulations_form.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1478030625432/installation_permit_4_22_15.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508550972948_installation_permit_4_22_15.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1457314222049/e-procurement_shopping_guide.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434821805_e-procurement_shopping_guide.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1504804392756/risd_rides_map.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434849143_risd_rides_map.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1507308949612/insurance_requirements_for_vendors_10_6_17.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434851655_insurance_requirements_for_vendors_10_6_17.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1502721723044/risd_international_assistance_insurance_id_card.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434847397_risd_international_assistance_insurance_id_card.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1504273247624/student_work_authorization_form_instructions.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434848247_student_work_authorization_form_instructions.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1506353785559/final_catering_menu_2017_9_25_17.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434849987_final_catering_menu_2017_9_25_17.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1442597925778/cake_orderform.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508435076152_cake_orderform17-18.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1440792763597/Student%20Employment%20Handbook%2015-16.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508551599128_Student%2520Employment%2520Handbook%252015-16.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1475261507451/100116.Menu%20for%20Web.pdf
new active link: https:https://my.risd.edu/pre_college/dining_locator/index

previously broken link: http://info.risd.edu/webhook-uploads/1474076453861/risd_code_of_conduct_2017_final.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434810879_risd_code_of_conduct_2017_final.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1478703506127/independent_contractor_form_updated_11_8_16.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434807377_independent_contractor_form_updated_11_8_16.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1498486467934/list_of_vendors_6_26_17.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434820977_list_of_vendors_6_26_17.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1508420780804/504_grievance_policy_updated_10_17_2017.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434818491_504_grievance_policy_updated_10_17_2017.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1486180847412/personal-alarms.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434832749_personal-alarms.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1486570544191/bicycle_scooter_registration.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508435107535_bicycle_scooter_registration.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1486183398245/operation_id.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434834394_operation_id.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1486183448570/national_crime_prevention_council.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434835212_national_crime_prevention_council.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1486183503872/redcross-training.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434835993_redcross-training.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1494251349862/payment_request_form_5_8_17.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434843060_payment_request_form_5_8_17.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1493835231853/honoriarium_payment_request_form.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434808149_honoriarium_payment_request_form.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1491405029348/tax_exempt_certificate_ri.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434840193_tax_exempt_certificate_ri.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1493832473776/tax_exemption_ma.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434843868_tax_exemption_ma.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1493832570020/tax_exemption_ny.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434844670_tax_exemption_ny.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1442252859831/tax_exemption_certificate_multi-jurisdictional.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508435089759_tax_exemption_certificate_multi-jurisdictional.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1493833259759/risd_w_9.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434845460_risd_w_9.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1493833352335/501c3.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434846545_501c3.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1491400365991/contract_authorization_form_final_april_2017.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434839410_contract_authorization_form_final_april_2017.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1506612306432/the_allied_group_stationery_ordering_guide.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434850823_the_allied_group_stationery_ordering_guide.pdf

previously broken link: http://info.risd.edu/webhook-uploads/1505318573869/risd_partner_hotels_quick_reference_sheet_9_13_17.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434831918_risd_partner_hotels_quick_reference_sheet_9_13_17.pdf

previously broken link: http://www.risd.edu/uploadedFiles/RISD_edu/Students/Public_Safety/bike-registration.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434833572_bike-registration.pdf

previously broken link: http://www.risd.edu/uploadedFiles/RISD_edu/Students/Public_Safety/operationID.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434834394_operation_id.pdf

previously broken link: http://www.risd.edu/uploadedFiles/RISD_edu/Students/Public_Safety/redcross-training.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508434835993_redcross-training.pdf

previously broken link: http://www.risd.edu/uploadedFiles/RISD_edu/Students/Public_Safety/parking_spaces_map.pdf
new active link: https://cdn.risd.systems/webhook-uploads/1508435033790_parking_spaces_map.pdf

**Comment by cmiller02** [comment]
I went through each link here - verifying that it was currently, purposefully, being linked to on info.risd.edu. Any links pulling up out-dated versions of forms, documents, etc. were deleted from GCP. This can now be closed.
