### ISSUE TITLE
generating an iterative site map for info

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#45]
@rubillionaire can you please configure info so that it publishes an auto-updating sitemap that we can ad to Google Search Console? (Like we have for www.risd.edu: http://www.risd.edu/www-risd-edu-sitemap.xml.)

Thanks!
-Carrie

**Comment by rubillionaire** [comment]
No problem, @cmiller02. This is an easy one. All webhook sites generate a sitemap, its just a matter of finding it. It can typically be found in the `robots.txt` file of a site. In this case, I had to make a small update to http://info.risd.edu/robots.txt, which now lists the site map as http://info.risd.edu/info-risd-edu-sitemap.xml

Let me know how that works, or if you need anything else.

**Comment by cmiller02** [comment]
I think this is good - what do you think @room421 ?

Thanks so much, @rubillionaire !

**Comment by cmiller02** [comment]
@rubillionaire - would it be possible to not include the offices links like these:

http://info.risd.edu/offices/
http://info.risd.edu/offices/page-2/
http://info.risd.edu/offices/page-3/ etc...

and also to not include these:
http://info.risd.edu/temporarypopup/
http://info.risd.edu/quicklinks/

Thanks!

**Comment by rubillionaire** [comment]
Most definitely, @cmiller02. These were just empty pages, so I deleted them from the templates. They are no longer part of the build process, so they are no longer in the sitemap.

**Comment by cmiller02** [comment]
This looks great now, @rubillionaire! Thanks for eliminating those empty pages. @room421 - all seems good with this now, so I believe we can close this issue.
