### ISSUE TITLE
change showing on info.risd.systems but not info.risd.edu

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#46]
Hey @rubillionaire - this is may be a shot in the dark, but it occurred to me that the Carr Haus Café page (the one where my change wasn't showing on info.risd.edu) is one of the only pages on info with a url that has an accent mark in it: http://info.risd.edu/carr-haus-caf%C3%A9/

So, I thought I'd try a change on the other one involving an accent mark: Portfolio Café and that change doesn't show on info.risd.edu either, yet I see it on info.risd.systems. 

Here are screenshots of Carr Haus first and then Portfolio. (I've highlighted what appears on systems that you then won't see on info.risd.edu.

![screen shot 2018-01-18 at 11 46 12 am](https://user-images.githubusercontent.com/14020234/35110330-8c5c7f2a-fc46-11e7-856b-b81cd88687ef.png)
![screen shot 2018-01-18 at 11 46 33 am](https://user-images.githubusercontent.com/14020234/35110331-8c6f6f72-fc46-11e7-8996-a56ea247f490.png)

![screen shot 2018-01-18 at 11 56 31 am](https://user-images.githubusercontent.com/14020234/35110406-bd8e3cf0-fc46-11e7-9239-9a568723a5b6.png)
![screen shot 2018-01-18 at 11 56 39 am](https://user-images.githubusercontent.com/14020234/35110407-bd98177a-fc46-11e7-9a75-c7d029d703a4.png)

**Comment by rubillionaire** [comment]
Ahh yeah this is a strange one. The pages are served and cached in a service named Fastly. Part of the build process is to purge the cache of pages that have been updated. For some reason, these pages were still being cached, so there is something up with the cache purge on these URLs. I was able to verify this by manually purging the Fastly cache for these two URLs.

I will leave this issue open and leave myself a note here to pick up by verifying how we can properly handle these URLs in code, so we don't have to worry about manually purging the cache for these pages. I'll try to do this early next week.

Thanks for noticing the patter, @cmiller02!

**Comment by rubillionaire** [comment]
@cmiller02 I found the bug in the cache purging subprocess of the build, and I think I've patched it in the commit above. The problem was improperly handling non-standard characters like the `é` in `Café` when making the cache purge request.

After applying the patch, I was able to add and remove a period to the end of the Carr Haus Café description. The changes were made on both the .systems & .edu URL. 

Give it another try, and let me know if you are seeing the changes propagate properly.

**Comment by cmiller02** [comment]
Hey @rubillionaire - not sure this is working yet. I put the two periods at the end of the office description for Carr Haus Cafe:

In CMS:
![screen shot 2018-01-24 at 8 55 44 am](https://user-images.githubusercontent.com/14020234/35335826-9946eed0-00e4-11e8-92ae-b01e26eadc49.png)

And that is showing on systems:
![screen shot 2018-01-24 at 8 57 40 am](https://user-images.githubusercontent.com/14020234/35335865-b42f2492-00e4-11e8-95cf-91b2c68d0aa6.png)

but not on info.risd.edu:
![screen shot 2018-01-24 at 8 57 58 am](https://user-images.githubusercontent.com/14020234/35335875-bb82b362-00e4-11e8-9e90-3e2b0b948dc5.png)

**Comment by rubillionaire** [comment]
Shoot! I tested this locally and didn't complete the push to the server. This should be in place. Sorry for the issues, but could you try this again?

**Comment by cmiller02** [comment]
No worries, @rubillionaire - I think we're all set now. I did updates to both Carr Haus and Portfolio successfully - edits showed on both systems and info.risd.edu. I'm going to close this out now. Thanks so much!
