### ISSUE TITLE
Please make the fax field NOT be a link

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#47]
@rubillionaire - can you please make it so the fax field is NOT a link. The fax field on the Media Group page came up as a broken link in Siteimprove, so that just brought my attention to the fact that it probably shouldn't be a link:

![screen shot 2018-02-13 at 9 49 46 am](https://user-images.githubusercontent.com/14020234/36155827-659f4c7a-10a3-11e8-867b-08ae417cfade.png)

Thank you!

**Comment by cmiller02** [comment]
ah! Now with it fixed I think it's perfect. And I'm glad that we'd be sticking to standards as well. Thanks @rubillionaire! This is good to go!

**Comment by rubillionaire** [comment]
Awesome! The change is now on info.risd.edu as well.
