### ISSUE TITLE
Please make search results greater than 100 results

### ISSUE THREAD

**Issue by cmiller02** [risd/wh-info#48]
@rubillionaire - quite a while ago Jay increased the maximum amount of search results returned for me. (Basically I periodically run the following search: "Key Contacts," which returns to me all pages who have the Contact Name field filled in. However, I think that we have 126 index entries on the homepage of info and I believe that more than 100 of those have the Contact Name filled in, but with the max at (I believe) 100 for the search results not all offices with a Contact Name field filled in show up. Can you increase the max to, maybe, 150?

**Comment by rubillionaire** [comment]
@cmiller02 I double checked and you are correct, we are only getting 100 results back. This is in spite of having the script set to request 200 items in return for each query. Unfortunately, its just the ceiling of the service. Swiftype will not return more than 100 items per query. It looks like they support paginated results, although its not how our search is implemented. We return one "page" worth of results.

That said, I would hope that adding more words to a user's search would help them drill down into what they want.

If you do ever need to have more than 100 items returned for a query, I would suggest using the search preview tool in the Swiftype dashboard. I searched "key contacts" there and was returned 103 results.

Here is the swiftype documentation where the search queries are documented. For your reference,  https://swiftype.com/documentation/site-search/searching

**Comment by cmiller02** [comment]
Thank you so much, @rubillionaire. This "key contacts" search is really for me, so I'm happy to go the Swiftype dashboard route. I think we're all good here, so I'm going to close this up. Really appreciate the documentation link!
